version: '3.7'
services:
  url-shortner-mysql-db:
    image: mysql:8.0.34
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=tinyURL
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=tinyurl
    ports:
      - 3306:3306
  